#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*""} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF
List samples in repository

$ rbbt workflow cmd Sample list

-h--help Print this help
EOF

rbbt_usage and exit 0 if options[:help]

puts Sample.all_samples * "\n"
